# Generated by: Neurodocker version 0.7.0
# Latest release: Neurodocker version 0.7.0
# Timestamp: 2021/08/29 20:31:12 UTC
#
# Thank you for using Neurodocker. If you discover any issues
# or ways to improve this software, please submit an issue or
# pull request on our GitHub repository:
#
#     https://github.com/ReproNim/neurodocker

FROM neurodebian:stretch

USER root

ARG DEBIAN_FRONTEND="noninteractive"

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker

ENTRYPOINT ["/neurodocker/startup.sh"]

ARG DEBIAN_FRONTEND="noninteractive"

LABEL maintainer="Fitlins Team"

ENV MKL_NUM_THREADS="1" \
    OMP_NUM_THREADS="1"

RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           unzip \
           curl \
           graphviz \
           wget \
           git-annex-standalone \
           git \
           vim \
           tig \
           git-annex-remote-rclone \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN test "$(getent passwd neuro)" || useradd --no-user-group --create-home --shell /bin/bash neuro
USER neuro

WORKDIR /home/neuro

ENV CONDA_DIR="/opt/miniconda-latest" \
    PATH="/opt/miniconda-latest/bin:$PATH"
RUN export PATH="/opt/miniconda-latest/bin:$PATH" \
    && echo "Downloading Miniconda installer ..." \
    && conda_installer="/tmp/miniconda.sh" \
    && curl -fsSL --retry 5 -o "$conda_installer" https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash "$conda_installer" -b -p /opt/miniconda-latest \
    && rm -f "$conda_installer" \
    && conda update -yq -nbase conda \
    && conda config --system --prepend channels conda-forge \
    && conda config --system --set auto_update_conda false \
    && conda config --system --set show_channel_urls true \
    && sync && conda clean -y --all && sync \
    && conda create -y -q --name neuro \
    && conda install -y -q --name neuro \
           "python=3.9" \
           "numpy" \
           "pytest" \
           "traits" \
           "pandas" \
           "matplotlib>=1.5.1" \
           "scikit-learn" \
           "scikit-image" \
           "seaborn" \
           "nbformat" \
           "nb_conda" \
    && sync && conda clean -y --all && sync

RUN conda install -y --channel leej3 --name neuro "afni-minimal" && sync && conda clean -y --all && sync

COPY [".", "/src/fitlins"]

USER root

RUN mkdir /work && chown -R neuro /src /work && chmod a+w /work

USER neuro

ARG VERSION

# RUN echo "$VERSION" > /src/fitlins/VERSION

RUN sed -i -e 's/crashfile_format = pklz/crashfile_format = txt/' /src/fitlins/fitlins/data/nipype.cfg

RUN bash -c "source activate neuro \
    &&   pip install --no-cache-dir -r \
             "/src/fitlins/requirements.txt"" \
    && rm -rf ~/.cache/pip/* \
    && sync \
    && sed -i '$isource activate neuro' $ND_ENTRYPOINT

RUN bash -c "source activate neuro \
    &&   pip install --no-cache-dir  \
             "/src/fitlins[all]"" \
    && rm -rf ~/.cache/pip/* \
    && sync \
    && sed -i '$isource activate neuro' $ND_ENTRYPOINT

WORKDIR /work

ENTRYPOINT ["/neurodocker/startup.sh", "fitlins"]

ARG BUILD_DATE

ARG VCS_REF

LABEL org.label-schema.build-date="$BUILD_DATE" \
      org.label-schema.name="FitLins" \
      org.label-schema.description="FitLins - Fit Linear Models to BIDS datasets" \
      org.label-schema.url="http://github.com/poldracklab/fitlins" \
      org.label-schema.vcs-ref="$VCS_REF" \
      org.label-schema.vcs-url="https://github.com/poldracklab/fitlins" \
      org.label-schema.version="$VERSION" \
      org.label-schema.schema-version="1.0"

RUN echo '{ \
    \n  "pkg_manager": "apt", \
    \n  "instructions": [ \
    \n    [ \
    \n      "base", \
    \n      "neurodebian:stretch" \
    \n    ], \
    \n    [ \
    \n      "arg", \
    \n      { \
    \n        "DEBIAN_FRONTEND": "noninteractive" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "label", \
    \n      { \
    \n        "maintainer": "Shashank Bansal" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "env", \
    \n      { \
    \n        "MKL_NUM_THREADS": "1", \
    \n        "OMP_NUM_THREADS": "1" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "install", \
    \n      [ \
    \n        "apt-utils", \
    \n        "unzip", \
    \n        "curl", \
    \n        "graphviz", \
    \n        "wget", \
    \n        "git-annex-standalone", \
    \n        "git", \
    \n        "vim", \
    \n        "tig", \
    \n        "git-annex-remote-rclone" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "neuro" \
    \n    ], \
    \n    [ \
    \n      "workdir", \
    \n      "/home/neuro" \
    \n    ], \
    \n    [ \
    \n      "miniconda", \
    \n      { \
    \n        "version": "latest", \
    \n        "create_env": "neuro", \
    \n        "conda_install": [ \
    \n          "python=3.9", \
    \n          "numpy", \
    \n          "pytest", \
    \n          "traits", \
    \n          "pandas", \
    \n          "matplotlib", \
    \n          "scikit-learn", \
    \n          "scikit-image", \
    \n          "seaborn", \
    \n          "nbformat", \
    \n          "nb_conda" \
    \n        ] \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "conda install -y --channel leej3 --name neuro \"afni-minimal\" && sync && conda clean -y --all && sync" \
    \n    ], \
    \n    [ \
    \n      "copy", \
    \n      [ \
    \n        ".", \
    \n        "/src/fitlins" \
    \n      ] \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "root" \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "mkdir /work && chown -R neuro /src /work && chmod a+w /work" \
    \n    ], \
    \n    [ \
    \n      "user", \
    \n      "neuro" \
    \n    ], \
    \n    [ \
    \n      "arg", \
    \n      { \
    \n        "VERSION": "" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "echo \"$VERSION\" > /src/fitlins/VERSION" \
    \n    ], \
    \n    [ \
    \n      "run", \
    \n      "sed -i -e '"'"'s/crashfile_format = pklz/crashfile_format = txt/'"'"' /src/fitlins/fitlins/data/nipype.cfg" \
    \n    ], \
    \n    [ \
    \n      "run_bash", \
    \n      "source activate neuro \\\\n      && pip install --no-cache-dir -r /src/fitlins/requirements.txt \\\\n      && rm -rf ~/.cache/pip/* \\\\n      && sync \\\\n      && sed -i \"$isource activate neuro\" $ND_ENTRYPOINT" \
    \n    ], \
    \n    [ \
    \n      "run_bash", \
    \n      "source activate neuro \\\\n      && pip install --no-cache-dir  \\\\n      \"/src/fitlins[all]\" \\\\n      && rm -rf ~/.cache/pip/* \\\\n      && sync \\\\n      && sed -i \"$isource activate neuro\" $ND_ENTRYPOINT" \
    \n    ], \
    \n    [ \
    \n      "workdir", \
    \n      "/work" \
    \n    ], \
    \n    [ \
    \n      "entrypoint", \
    \n      "/neurodocker/startup.sh fitlins" \
    \n    ], \
    \n    [ \
    \n      "arg", \
    \n      { \
    \n        "BUILD_DATE": "" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "arg", \
    \n      { \
    \n        "VCS_REF": "" \
    \n      } \
    \n    ], \
    \n    [ \
    \n      "label", \
    \n      { \
    \n        "org.label-schema.build-date": "$BUILD_DATE", \
    \n        "org.label-schema.name": "FitLins", \
    \n        "org.label-schema.description": "FitLins - Fit Linear Models to BIDS datasets", \
    \n        "org.label-schema.url": "http://github.com/poldracklab/fitlins", \
    \n        "org.label-schema.vcs-ref": "$VCS_REF", \
    \n        "org.label-schema.vcs-url": "https://github.com/poldracklab/fitlins", \
    \n        "org.label-schema.version": "$VERSION", \
    \n        "org.label-schema.schema-version": "1.0" \
    \n      } \
    \n    ] \
    \n  ] \
    \n}' > /neurodocker/neurodocker_specs.json
