[build-system]
requires = ["setuptools>=77", "versioneer[toml]"]
build-backend = "setuptools.build_meta"

[project]
name = "fitlins"
authors = [{name = "Christopher J. Markiewicz", email = "crn.poldracklab@gmail.com"}]
description = "Fit Linear Models to BIDS Datasets"
license = "BSD-3-Clause"
readme = "README.rst"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
urls = {Homepage = "https://github.com/poldracklab/fitlins"}
requires-python = ">=3.11"
dependencies = [
    "nibabel>=5.1",
    "nipype>=1.8.6",
    "seaborn>=0.13",
    "numpy>=1.25",
    "nilearn~=0.9.1",
    "pandas>=2.1",
    "tables>=3.9.1",
    "pybids>=0.16.0",
    "jinja2>=3.1.3",
    "setuptools",
]
dynamic = ["version"]

[project.optional-dependencies]
duecredit = ["duecredit"]
test = [
    "coverage",
    "pytest",
    "pytest-cov",
]
workflow = ["fitlins[test]"]
docs = [
    "sphinx~=4.5.0",
    "sphinxcontrib-apidoc~=0.3.0",
    "sphinx-argparse~=0.3.1",
    "nbsphinx~=0.8.8",
    "texext~=0.6.6",
    "myst-parser~=0.17.0",
]
style = ["flake8 >= 3.7.0"]
all = [
    "fitlins[docs,duecredit,style,test]",
]

[project.scripts]
fitlins = "fitlins.cli.run:main"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages]
find = {namespaces = false}

[tool.setuptools.package-data]
fitlins = [
    "data/*.json",
    "data/*.tpl",
    "data/nipype.cfg",
    "data/conte69/*.gii",
]

[tool.setuptools.exclude-package-data]
"*" = ["examples"]

[tool.versioneer]
VCS = "git"
style = "pep440-pre"
versionfile_source = "fitlins/_version.py"
versionfile_build = "fitlins/_version.py"
tag_prefix = ""
parentdir_prefix = ""

[tool.flake8]
max-line-length = "99"
doctests = "True"
exclude = "*build/"
per-file-ignores = """
**/__init__.py : F401"""

[tool.coverage.run]
branch = true
omit = ["*/tests/*"]

[tool.black]
line-length = 99
skip-string-normalization = true
extend-exclude = '_version.py|versioneer.py'
